### ISSUE TITLE
parsing malformed json websocket data

### ISSUE THREAD

**Issue by qexia** [mithatcy/yeni-guard-botu#1]
This fixes issue https://github.com/JKorf/CryptoExchange.Net/issues/146 and makes the WebSocket ProcessMessage handle malformed json data.

The original code had a fallback, if it can't be parsed as JSON, add quotes around it and create a JSON object with the value as a single string from the result. I believe that is the intent.

I am keeping the same intent, but changed the code so that it explicitly creates a JValue string object from the result string. This causes malformed json strings as in issue https://github.com/JKorf/CryptoExchange.Net/issues/146 to be successfully parsed and returned as JToken.

**Comment by mithatyagmuroglu** [comment]
> This fixes issue [JKorf/CryptoExchange.Net#146](https://github.com/JKorf/CryptoExchange.Net/issues/146) and makes the WebSocket ProcessMessage handle malformed json data.
> 
> The original code had a fallback, if it can't be parsed as JSON, add quotes around it and create a JSON object with the value as a single string from the result. I believe that is the intent.
> 
> I am keeping the same intent, but changed the code so that it explicitly creates a JValue string object from the result string. This causes malformed json strings as in issue [JKorf/CryptoExchange.Net#146](https://github.com/JKorf/CryptoExchange.Net/issues/146) to be successfully parsed and returned as JToken.
