### ISSUE TITLE
asdsadadada

### ISSUE THREAD

**Issue by qexia** [mithatcy/yeni-guard-botu#3]
- _sadadadadadadads**asdsadasdasdadsdadasdasdadasdadada**_dadaddasdadad

> adsasdasdasdada[asdadasdada](url)

[ ] dasdadasdsadadasdadadadddadadaddasdadads`sadda `

**Comment by mithatyagmuroglu** [comment]
- asdddddddddddddasdadadasdasdsadasdasdadada_sadad_asdsdadadadasdsadasdada

- [ ] asdasdadadadadadasda### 

> 

- [ ] 

- [ ] `_sadadsadsadadsadadadasd**dsadadsadsadadadsdsadadsadadssadsadadaddasdasdadasdadsasdasda**adsasdasdadasdaasdasdasdasdadadadaddasdaddsasadadsadsadasda_`
